name: Build and Deploy Flask App with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build Docker image
      run: |
        docker build -t my-flask-app .

    - name: Run Flask app container
      run: |
        docker run -d -p 8080:8080 --name flask-container my-flask-app

    - name: Wait for Flask app to be up
      run: |
        sleep 15  # Give it some time to start up

    - name: Test Flask app is running
      run: |
        curl --fail http://localhost:8080/top-actors || exit 1

    - name: Stop Flask app container
      run: |
        docker stop flask-container
        docker rm flask-container

